### ISSUE TITLE
Nuget package for net6.0-windows

### ISSUE THREAD

**Issue by ekalchev** [microsoft/XamlBehaviorsWpf#102]
Currently there is no Nuget package for target platform net6.0-windows. When you are planning to have one?

**Comment by brianlagunas** [comment]
I think we should.  I also think we should update to .NET 4.6.2 since every version prior is out of support. 

I'm also tempted to drop .NET Core 3.1 (support ends Dec 13, 2022) and .NET 5 (support ended) and move to NET 6.

Since no one from Microsoft has been active on this repo, I say ask for forgiveness rather than permission 😄 

Community thoughts?

**Comment by skst** [comment]
I would like to see a NuGet package for .NET 7.

**Comment by brianlagunas** [comment]
We have updated to .NET 4.6.2 AND .net 6.0. I did not add .NET 7 as it is STS. Plus, the .net 6 will work just fine in .net 7.
