### ISSUE TITLE
Samples solution fails to build on fresh checkout

### ISSUE THREAD

**Issue by datchung** [Microsoft/XamlBehaviorsWpf#31]
**Describe the bug**
The [Samples](https://github.com/Microsoft/XamlBehaviorsWpf/tree/master/samples) solution fails to build on fresh checkout.

**To Reproduce**
1. Download XamlBehavioursWpf as a zip
2. Unzip
3. Open `samples\XAMLBehaviorsSample\XAMLBehaviorsSample.sln`
4. Build or rebuild solution.

**Expected behavior**
Build should succeed.

**Actual behavior**
Build fails. See screenshot below.

**Screenshots**
![behaviors](https://user-images.githubusercontent.com/8369243/53588336-b5850580-3b5a-11e9-9066-9aec1b5c619f.PNG)

**Comment by PedroLamas** [comment]
The thing is, that is *not* a checkout! When you download the repo as a zip file, it gets stripped from any git related information, so the build fails because of that!

If you do a proper git checkout then the build will work just fine.

Alternatively, just run `git init .` on the root folder and it will build just fine.
