### ISSUE TITLE
External events can be referenced

### ISSUE THREAD

**Issue by rts62** [microsoft/XamlBehaviorsWpf#91]
**Is your feature request related to a problem? Please describe.**
Can previously existing external event references be used?

**Describe the solution you'd like**
External events can be referenced

**Describe alternatives you've considered**
Can use setter to call external events

**Additional context**

[ref:stackoverflow](https://stackoverflow.com/questions/29591574/move-interaction-behaviors-to-style-template-or-something-else)

```xaml
<Page.Resources>
    <i:BehaviorCollection x:Key="behaviors">
        <core:EventTriggerBehavior EventName="Tapped">
            <core:InvokeCommandAction Command="{Binding SetModeToAll}" />
        </core:EventTriggerBehavior>
    </i:BehaviorCollection>

    <Style TargetType="TextBlock" x:Key="textblockstyle">
        <Setter Property="i:Interaction.Behaviors" Value="{StaticResource behaviors}">
        </Setter>
    </Style>
</Page.Resources>

<Grid x:Name="LayoutRoot" Background="Transparent">
    <TextBlock Text="Testing" Foreground="Red" FontSize="20" Style="{StaticResource textblockstyle}">
    </TextBlock >
</Grid>
```

```xaml
<Button>
    <Button.Triggers> 
        <Setter Property="Behaviors:Interaction.Triggers" >
            <Setter.Value> // error : must be TriggerCollection
                <Behaviors:DataTrigger Binding="{Binding Content}" Value="@all">
                <Behaviors:InvokeCommandAction Command="{Binding SetModeToAll}" />
                </Behaviors:DataTrigger>
            </Setter.Value>
        </Setter>
    </Button.Triggers>
</Button>

```

**Comment by brianlagunas** [comment]
Behaviors cannot be used in styles because they are are read-only properties. This is by design and will most likely never change.

However, there are ways around this issue.  The most common approach to getting around this limitation of Behaviors/Trigger is to create your own Attached Property to use instead.  See this [SO post](https://stackoverflow.com/questions/27715798/behaviors-are-not-working-properly-inside-style-setter/29808226#29808226) as an example.
